package net.gozar.app

enum class Lang { EN, FA }

private val faDigits = charArrayOf('۰','۱','۲','۳','۴','۵','۶','۷','۸','۹')

fun localizeDigits(text: String, lang: Lang): String {
    if (lang != Lang.FA) return text
    val sb = StringBuilder(text.length)
    for (c in text) sb.append(if (c in '0'..'9') faDigits[c - '0'] else c)
    return sb.toString()
}
object Strings {

    private val en = mapOf(
        "connection" to "Connection",
        "settings" to "Settings",
        "app_title" to "GNET",
        "appearance" to "Appearance",
        "choose_server" to "Choose server",
        "add_config_title" to "Add config",
        "data_usage" to "Data usage",
        "selected_server" to "Selected server",
        "tap_choose" to "Tap to choose a server",
        "connect" to "Connect",
        "connecting_cancel" to "Connecting…  (tap to cancel)",
        "disconnect" to "Disconnect",
        "real_delay" to "Ping",
        "speed_test" to "Speed test",
        "testing" to "Testing…",
        "delay_failed" to "Timeout",
        "speed_failed" to "Speed: failed",
        "status_disconnected" to "Disconnected",
        "conn_disconnected" to "Disconnected",
        "conn_connected_for" to "Connected for %s",
        "status_connecting" to "Connecting…",
        "status_connected" to "Connected",
        "status_error" to "Error",
        "paste_links" to "Paste one or many links (one per line)",
        "add" to "Add",
        "paste_clipboard" to "Paste from clipboard",
        "add_manually" to "Add manually",
        "add_warp" to "Add WARP",
        "warp_added" to "WARP added",
        "warp_failed" to "WARP sign-up failed",
        "scan_warp" to "Scan Cloudflare IPs",
        "scan_title" to "Cloudflare IP scanner",
        "scan_sub" to "Find clean Cloudflare edge IPs that work here",
        "scan_intro" to "Samples Cloudflare's IP ranges and keeps the ones reachable from your network, ranked by latency. Tap an IP to copy it — use it as a clean IP for Cloudflare-fronted servers.",
        "scan_count" to "How many IPs to scan",
        "scan_start" to "Start scan",
        "scanning" to "Scanning…",
        "scan_done" to "%d clean IPs found",
        "scan_none" to "No reachable IPs found — scan again",
        "copy_all" to "Copy all",
        "copied" to "Copied",
        "copied_all" to "All IPs copied",
        "tools" to "Tools",
        "test_all" to "Test all",
        "test_completed" to "Test completed",
        "adding" to "Adding…",
        "added_configs" to "Added %d config(s)",
        "added_sub" to "Added a sub with %d configs",
        "clipboard_empty" to "Clipboard is empty",
        "pasted" to "Pasted from clipboard",
        "manual_configs" to "Manual configs",
        "refresh" to "Refresh",
        "remove" to "Remove",
        "delete" to "Delete",
        "edit" to "Edit",
        "share" to "Share",
        "share_clipboard" to "Share to clipboard",
        "share_app" to "Share to app",
        "selected" to "selected",
        "delete_selected_q" to "Delete the selected configs?",
        "copied" to "Copied to clipboard",
        "edit_config_title" to "Edit config",
        "edit_sub_name" to "Edit name",
        "service_name" to "gRPC service name",
        "mode" to "Mode",
        "alpn" to "ALPN (comma-separated)",
        "fingerprint" to "Fingerprint",
        "xray_logs" to "Xray logs",
        "xray_logs_sub" to "View the engine’s runtime logs",
        "clear" to "Clear",
        "no_logs" to "No logs yet",
        "stab_title" to "Internet Quality Test",
        "stab_sub" to "Speed, ping, jitter and quality rating",
        "stab_start" to "Start test",
        "stab_ping" to "Ping",
        "stab_dl_ping" to "Download ping",
        "stab_ul_ping" to "Upload ping",
        "stab_jitter" to "Jitter",
        "stab_idle_latency" to "Idle latency",
        "stab_dl_latency" to "Download latency",
        "stab_ul_latency" to "Upload latency",
        "stab_direct_checking" to "Checking direct network\u2026",
        "stab_direct_stable" to "Direct network is stable",
        "stab_direct_unstable" to "Direct network is unstable",
        "stab_direct_offline" to "Internet connection is off",
        "stab_last_test" to "Last test:",
        "stab_quality" to "Quality",
        "stab_gaming" to "Gaming",
        "stab_browsing" to "Web browsing",
        "stab_streaming" to "Streaming",
        "stab_calling" to "Video calling",
        "stab_through_tunnel" to "Testing through the tunnel",
        "stab_direct" to "Testing your direct connection",
        "stab_failed" to "Test failed — check your connection",
        "stab_testing_server" to "Testing server:",
        "stab_no_server" to "Select a server to test",
        "default_order" to "Default order",
        "fastest_first" to "Fastest first",
        "routing" to "Routing",
        "split_title" to "Split routing (Iran direct)",
        "split_sub" to "Iranian sites bypass the tunnel and connect directly.",
        "fragment_title" to "Fragment (anti-DPI)",
        "fragment_sub" to "Splits the TLS handshake to evade SNI filtering. Try it if a server won't connect.",
        "sniffing_title" to "Turn on Sniffing",
        "sniffing_type" to "Sniffing type",
        "sniffing_sub" to "Connects using the domain detected from traffic instead of the raw IP. Can help some servers connect correctly.",
        "takes_effect" to "Changes take effect on the next connection.",
        "language" to "Language",
        "about" to "About",
        "about_sub" to "Version, developer & privacy policy",
        "app_version" to "App version",
        "xray_version" to "Xray core",
        "telegram_support" to "Telegram support",
        "privacy_policy" to "Privacy Policy",
        "developer" to "Developer",
        "source_code" to "Source code",
        "check_updates" to "Check for updates",
        "checking_updates" to "Checking…",
        "up_to_date" to "You're on the latest version",
        "update_available" to "Update available: %s",
        "update_failed" to "Couldn't check — try again",
        "update_now" to "Update",
        "later" to "Later",
        "auto_refresh" to "Auto-refresh subscriptions",
        "auto_refresh_off" to "Off",
        "every_hour" to "Every %s hour",
        "every_hours" to "Every %s hours",
        "all_time_total" to "All-time total",
        "tap_ranges" to "Tap for ranges and custom dates  ›",
        "range" to "Range",
        "today" to "Today",
        "range_7d" to "7d",
        "range_30d" to "30d",
        "custom_range" to "Custom range",
        "from" to "From",
        "to" to "To",
        "custom_hint" to "Up to 2 days shows hourly detail; longer shows daily. Hourly history is kept ~30 days.",
        "download" to "Download",
        "upload" to "Upload",
        "total" to "Total",
        "no_data_range" to "No data for this range.",
        "tunnel_only" to "Counts only traffic sent through the tunnel.",
        "peak_per_bar" to "Peak %s per bar",
        "name_optional" to "Name (optional)",
        "protocol" to "Protocol",
        "address" to "Address",
        "port" to "Port",
        "uuid" to "UUID",
        "password" to "Password",
        "enc_method" to "Encryption method",
        "flow_optional" to "Flow (optional)",
        "network" to "Network",
        "security" to "Security",
        "sni" to "SNI / server name",
        "public_key" to "Public key (pbk)",
        "short_id" to "Short ID (sid)",
        "ws_path" to "WS path",
        "ws_host" to "WS host header",
        "cancel" to "Cancel",
        "save" to "Save",
        "err_address" to "Address is required",
        "err_port" to "Port must be 1–65535",
        "err_uuid" to "UUID is required",
        "err_password" to "Password is required",
        "fetching_sub" to "Fetching subscription…",
        "no_configs" to "No configs found",
        "fetch_failed" to "Fetch failed",
        "parse_none" to "Couldn't parse any links",
        "left" to "left",
        "of" to "of",
        "expires_in" to "expires in",
        "unit_b" to "B",
        "unit_kb" to "KB",
        "unit_mb" to "MB",
        "unit_gb" to "GB",
        "unit_ms" to "ms",
        "unit_mbps" to "Mbps",
        "unit_per_sec" to "/s",
        "unit_days" to "d",
        "welcome_tagline" to "GNET, a tool to pass through restrictions",
        "welcome_dev" to "Developed by Oracle VPN",
        "per_app" to "Per-app proxy",
        "per_app_sub" to "Choose which apps use the VPN",
        "per_app_mode" to "Mode",
        "per_app_off" to "Off (all apps use VPN)",
        "per_app_allow" to "Only selected apps",
        "per_app_block" to "All apps except selected",
        "per_app_off_hint" to "Per-app routing is off — every app uses the VPN.",
        "search_apps" to "Search apps",
        "loading_apps" to "Loading apps…"
    )

    private val fa = mapOf(
        "connection" to "اتصال",
        "settings" to "تنظیمات",
        "app_title" to "GNET",
        "choose_server" to "انتخاب سرور",
        "add_config_title" to "افزودن کانفیگ",
        "data_usage" to "مصرف داده",
        "selected_server" to "سرور انتخاب‌شده",
        "tap_choose" to "برای انتخاب سرور بزنید",
        "connect" to "اتصال",
        "connecting_cancel" to "در حال اتصال…  (برای لغو بزنید)",
        "disconnect" to "قطع اتصال",
        "real_delay" to "پینگ",
        "speed_test" to "تست سرعت",
        "testing" to "در حال تست…",
        "delay_failed" to "تایم‌اوت",
        "speed_failed" to "سرعت: ناموفق",
        "status_disconnected" to "قطع",
        "conn_disconnected" to "قطع شده",
        "conn_connected_for" to "متصل به مدت %s",
        "status_connecting" to "در حال اتصال…",
        "status_connected" to "متصل",
        "status_error" to "خطا",
        "paste_links" to "یک یا چند لینک را وارد کنید (هر کدام در یک خط)",
        "add" to "افزودن",
        "paste_clipboard" to "وارد کردن از کلیپ‌بورد",
        "add_manually" to "افزودن دستی",
        "add_warp" to "افزودن WARP",
        "warp_added" to "WARP اضافه شد",
        "warp_failed" to "ثبت WARP ناموفق بود",
        "scan_warp" to "اسکن آی‌پی‌های کلودفلر",
        "scan_title" to "اسکنر آی‌پی کلودفلر",
        "scan_sub" to "پیدا کردن آی‌پی‌های تمیز کلودفلر که اینجا کار می‌کنند",
        "scan_intro" to "از رنج آی‌پی های کلودفلر نمونه‌برداری می‌کند و آن‌هایی را که از شبکه شما در دسترس‌اند بر اساس تأخیر مرتب می‌کند. برای کپی روی آی‌پی بزنید — به‌عنوان آی‌پی تمیز برای سرورهای پشت کلودفلر استفاده کنید.",
        "scan_count" to "چند آی‌پی اسکن شود",
        "scan_start" to "شروع اسکن",
        "scanning" to "در حال اسکن…",
        "scan_done" to "%d آی‌پی سالم پیدا شد",
        "scan_none" to "آی‌پی در دسترسی پیدا نشد — دوباره اسکن کنید",
        "copy_all" to "کپی همه",
        "copied" to "کپی شد",
        "copied_all" to "همه آی‌پی‌ها کپی شد",
        "tools" to "ابزارها",
        "test_all" to "تست همه",
        "test_completed" to "تست کامل شد",
        "adding" to "در حال افزودن…",
        "added_configs" to "%d کانفیگ افزوده شد",
        "added_sub" to "ساب با %d کانفیگ افزوده شد",
        "clipboard_empty" to "کلیپ‌بورد خالی است",
        "pasted" to "از کلیپ‌بورد چسبانده شد",
        "manual_configs" to "کانفیگ‌های دستی",
        "refresh" to "بروزرسانی",
        "remove" to "حذف",
        "delete" to "حذف",
        "edit" to "ویرایش",
        "share" to "اشتراک‌گذاری",
        "share_clipboard" to "اشتراک در کلیپ‌بورد",
        "share_app" to "اشتراک با برنامه",
        "selected" to "انتخاب‌شده",
        "delete_selected_q" to "کانفیگ‌های انتخاب‌شده حذف شوند؟",
        "copied" to "در کلیپ‌بورد کپی شد",
        "edit_config_title" to "ویرایش کانفیگ",
        "edit_sub_name" to "ویرایش نام",
        "service_name" to "نام سرویس gRPC",
        "mode" to "حالت",
        "alpn" to "ALPN (با کاما جدا کنید)",
        "fingerprint" to "اثر انگشت",
        "xray_logs" to "لاگ‌های Xray",
        "xray_logs_sub" to "مشاهده لاگ‌های اجرای موتور",
        "clear" to "پاک کردن",
        "no_logs" to "هنوز لاگی نیست",
        "stab_title" to "تست کیفیت اینترنت",
        "stab_sub" to "سرعت، پینگ، جیتر و کیفیت",
        "stab_start" to "شروع تست",
        "stab_ping" to "پینگ",
        "stab_dl_ping" to "پینگ دانلود",
        "stab_ul_ping" to "پینگ آپلود",
        "stab_jitter" to "جیتر",
        "stab_idle_latency" to "تأخیر در حالت بی‌کاری",
        "stab_dl_latency" to "تأخیر دانلود",
        "stab_ul_latency" to "تأخیر آپلود",
        "stab_direct_checking" to "در حال بررسی شبکه مستقیم\u2026",
        "stab_direct_stable" to "شبکه مستقیم پایدار است",
        "stab_direct_unstable" to "شبکه مستقیم ناپایدار است",
        "stab_direct_offline" to "اتصال اینترنت قطع است",
        "stab_last_test" to "آخرین تست:",
        "stab_quality" to "کیفیت",
        "stab_gaming" to "بازی",
        "stab_browsing" to "مرور وب",
        "stab_streaming" to "استریم",
        "stab_calling" to "تماس تصویری",
        "stab_through_tunnel" to "تست از طریق تونل",
        "stab_direct" to "تست اتصال مستقیم",
        "stab_failed" to "تست ناموفق بود — اتصال خود را بررسی کنید",
        "stab_testing_server" to "سرور تست:",
        "stab_no_server" to "برای تست یک سرور انتخاب کنید",
        "default_order" to "ترتیب پیش‌فرض",
        "fastest_first" to "سریع‌ترین اول",
        "routing" to "مسیریابی",
        "split_title" to "مسیریابی تفکیکی (سایت های ایرانی مستقیم)",
        "split_sub" to "سایت‌های ایرانی بدون تونل و مستقیم وصل می‌شوند.",
        "fragment_title" to "فرگمنت (ضد DPI)",
        "fragment_sub" to "دست‌دادن TLS را تکه‌تکه می‌کند تا از فیلترینگ SNI عبور کند. اگر سروری وصل نشد امتحان کنید.",
        "sniffing_title" to "روشن کردن Sniffing",
        "sniffing_type" to "نوع Sniffing",
        "sniffing_sub" to "به‌جای IP خام، با دامنه‌ای که از ترافیک تشخیص داده می‌شود متصل می‌شود. می‌تواند به اتصال درست برخی سرورها کمک کند.",
        "takes_effect" to "تغییرات از اتصال بعدی اعمال می‌شوند.",
        "language" to "زبان",
        "about" to "درباره",
        "about_sub" to "نسخه، توسعه‌دهنده و حریم خصوصی",
        "app_version" to "نسخه برنامه",
        "xray_version" to "هسته Xray",
        "telegram_support" to "پشتیبانی تلگرام",
        "privacy_policy" to "سیاست حریم خصوصی",
        "developer" to "توسعه‌دهنده",
        "source_code" to "کد منبع",
        "check_updates" to "بررسی بروزرسانی",
        "checking_updates" to "در حال بررسی…",
        "up_to_date" to "نسخهٔ شما به‌روزترین است",
        "update_available" to "بروزرسانی موجود: %s",
        "update_failed" to "بررسی ناموفق بود — دوباره تلاش کنید",
        "update_now" to "بروزرسانی",
        "later" to "بعداً",
        "auto_refresh" to "بروزرسانی خودکار اشتراک‌ها",
        "auto_refresh_off" to "خاموش",
        "every_hour" to "هر %s ساعت",
        "every_hours" to "هر %s ساعت",
        "all_time_total" to "مجموع کل",
        "tap_ranges" to "برای بازه‌ها و تاریخ دلخواه بزنید  ›",
        "range" to "بازه",
        "today" to "امروز",
        "range_7d" to "۷ روز",
        "range_30d" to "۳۰ روز",
        "custom_range" to "بازه دلخواه",
        "from" to "از",
        "to" to "تا",
        "custom_hint" to "تا ۲ روز جزئیات ساعتی و بیشتر از آن روزانه نمایش داده می‌شود. تاریخچه ساعتی حدود ۳۰ روز نگه داشته می‌شود.",
        "download" to "دانلود",
        "upload" to "آپلود",
        "total" to "مجموع",
        "no_data_range" to "داده‌ای برای این بازه نیست.",
        "tunnel_only" to "فقط ترافیک عبوری از تونل شمارش می‌شود.",
        "peak_per_bar" to "اوج %s در هر ستون",
        "name_optional" to "نام (اختیاری)",
        "protocol" to "پروتکل",
        "address" to "آدرس",
        "port" to "پورت",
        "uuid" to "UUID",
        "password" to "رمز",
        "enc_method" to "روش رمزگذاری",
        "flow_optional" to "Flow (اختیاری)",
        "network" to "شبکه",
        "security" to "امنیت",
        "sni" to "SNI / نام سرور",
        "public_key" to "کلید عمومی (pbk)",
        "short_id" to "شناسه کوتاه (sid)",
        "ws_path" to "مسیر WS",
        "ws_host" to "هدر Host برای WS",
        "cancel" to "لغو",
        "save" to "ذخیره",
        "err_address" to "آدرس الزامی است",
        "err_port" to "پورت باید بین ۱ تا ۶۵۵۳۵ باشد",
        "err_uuid" to "UUID الزامی است",
        "err_password" to "رمز الزامی است",
        "fetching_sub" to "در حال دریافت ساب…",
        "no_configs" to "کانفیگی پیدا نشد",
        "fetch_failed" to "دریافت ناموفق بود",
        "parse_none" to "هیچ لینکی خوانده نشد",
        "left" to "باقی‌مانده",
        "of" to "از",
        "expires_in" to "انقضا در",
        "unit_b" to "بایت",
        "unit_kb" to "کیلوبایت",
        "unit_mb" to "مگابایت",
        "unit_gb" to "گیگابایت",
        "unit_ms" to "میلی‌ثانیه",
        "unit_mbps" to "مگابیت بر ثانیه",
        "unit_per_sec" to " بر ثانیه",
        "unit_days" to "روز",
        "welcome_tagline" to "جی‌نت، ابزاری برای گذر از محدودیت‌ها",
        "welcome_dev" to "توسعه داده شده توسط اوراکل وی‌پی‌ان",
        "per_app" to "پروکسی برنامه‌ها",
        "per_app_sub" to "انتخاب کنید کدام برنامه‌ها از وی‌پی‌ان استفاده کنند",
        "per_app_mode" to "حالت",
        "per_app_off" to "خاموش (همه برنامه‌ها)",
        "per_app_allow" to "فقط برنامه‌های انتخاب‌شده",
        "per_app_block" to "همه به‌جز انتخاب‌شده‌ها",
        "per_app_off_hint" to "مسیریابی per-app خاموش است — همه برنامه‌ها از وی‌پی‌ان استفاده می‌کنند.",
        "search_apps" to "جستجوی برنامه‌ها",
        "loading_apps" to "در حال بارگذاری برنامه‌ها…",
    )

    fun get(lang: Lang, key: String): String =
        (if (lang == Lang.FA) fa[key] else en[key]) ?: en[key] ?: key
}